application: mtp-lastfm
version: 1
runtime: python
api_version: 1

handlers:
    
- url: /css
  static_dir: static/css

- url: /images
  static_dir: static/images

- url: /api/.*
  script: api.py
  
- url: /.*
  script: webinterface.py


  
