#! /usr/bin/env python
import os
import sys
import optparse
import gtk
import pygtk


#decide if we have been distributed in a deb or sitting in the source dir
if os.path.abspath(__file__) == "/usr/bin/mtp-lastfm":
    sys.path.append("/usr/share/mtp-lastfm")

import localisation
_ = localisation.set_get_text()
from mtplastfm import MTPLastfmGTK

__author__ = ("Daniel Woodhouse <wodemoneke@gmail.com>","Saku Laukkanen <saku.laukkanen@jakelupaketti.net>")
__version__ = "0.80.1"
__version__ = "0.80"

parser = optparse.OptionParser(version="mtp-lastfm %s by %s" % (__version__, ', '.join(__author__)))
parser.add_option('--error-log', '-e', action="store_true", help=_("logs all stderr messages to ~/.mtp-lastfm/error.log")) 
parser.add_option('--test-mode', '-t', action="store_true", help=_("disables connections to last.fm for offline debugging"))
options, args = parser.parse_args()

mtp = MTPLastfmGTK(author=__author__,
                   version=__version__, error_log=options.error_log,
                   test_mode=options.test_mode)
gtk.main()


