# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.35
#
# Don't modify this file, modify the SWIG interface instead.
# This file is compatible with both classic and new-style classes.

import _mtpconnect
import new
new_instancemethod = new.instancemethod
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'PySwigObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError,name

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

import types
try:
    _object = types.ObjectType
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0
del types


open_device = _mtpconnect.open_device
close_device = _mtpconnect.close_device
reset_device = _mtpconnect.reset_device
get_manufacturer = _mtpconnect.get_manufacturer
get_model = _mtpconnect.get_model
get_libmtp_version = _mtpconnect.get_libmtp_version
get_tracks = _mtpconnect.get_tracks
get_track_count = _mtpconnect.get_track_count
next_track = _mtpconnect.next_track
get_friendly_name = _mtpconnect.get_friendly_name
get_artist = _mtpconnect.get_artist
get_title = _mtpconnect.get_title
get_album = _mtpconnect.get_album
get_duration = _mtpconnect.get_duration
get_item_id = _mtpconnect.get_item_id
get_rating = _mtpconnect.get_rating
get_track_number = _mtpconnect.get_track_number
get_usecount = _mtpconnect.get_usecount
is_valid_track = _mtpconnect.is_valid_track


